// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8W5Hb-9KAcZ6mL7zOISDkGMCHdJtNOTQ',
    appId: '1:287016054500:web:5677eb974534822324c6f1',
    messagingSenderId: '287016054500',
    projectId: 'cars-app-project',
    authDomain: 'cars-app-project.firebaseapp.com',
    storageBucket: 'cars-app-project.appspot.com',
    measurementId: 'G-3KY72BQR6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAonF97JqWm9NDs9BLOC0SUQJdgkKuFfJk',
    appId: '1:287016054500:android:0c55dd8133764e0424c6f1',
    messagingSenderId: '287016054500',
    projectId: 'cars-app-project',
    storageBucket: 'cars-app-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFYDONntE52tKuTfB9NlDjCxcD--nvIg8',
    appId: '1:287016054500:ios:0ba4bb806f42c21e24c6f1',
    messagingSenderId: '287016054500',
    projectId: 'cars-app-project',
    storageBucket: 'cars-app-project.appspot.com',
    iosBundleId: 'com.example.cars',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFYDONntE52tKuTfB9NlDjCxcD--nvIg8',
    appId: '1:287016054500:ios:0ba4bb806f42c21e24c6f1',
    messagingSenderId: '287016054500',
    projectId: 'cars-app-project',
    storageBucket: 'cars-app-project.appspot.com',
    iosBundleId: 'com.example.cars',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8W5Hb-9KAcZ6mL7zOISDkGMCHdJtNOTQ',
    appId: '1:287016054500:web:1be452353643f85b24c6f1',
    messagingSenderId: '287016054500',
    projectId: 'cars-app-project',
    authDomain: 'cars-app-project.firebaseapp.com',
    storageBucket: 'cars-app-project.appspot.com',
    measurementId: 'G-4WTS8SJ220',
  );
}
